apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: otel-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-credentials
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "otel", "-d", "oteldb"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "otel", "-d", "oteldb"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: init-sql
          configMap:
            name: postgres-init