apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: otel-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory
          image: otel-shop/inventory:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 18081
              name: http
          env:
            - name: PORT
              value: "18081"
            - name: DATABASE_URL
              value: postgres://otel:otel@postgres:5432/oteldb?sslmode=disable
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: otel-collector:14317
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1.0"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10