apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: otel-shop
spec:
  type: NodePort
  selector:
    app: payment-service
  ports:
    - name: http
      port: 18082
      targetPort: http
      nodePort: 18082