apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: otel-shop
data:
  config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14317
          http:
            endpoint: 0.0.0.0:14318
    processors:
      batch: {}
    exporters:
      otlp/jaeger:
        endpoint: jaeger:4317
        tls:
          insecure: true
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger]