apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: otel-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.159.0
          args: ["--config=/etc/otelcol/config.yaml"]
          ports:
            - containerPort: 14317
              name: otlp-grpc
            - containerPort: 14318
              name: otlp-http
            - containerPort: 13133
              name: healthcheck
          volumeMounts:
            - name: config
              mountPath: /etc/otelcol
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: otel-collector-config